<script lang="ts">
	import '../app.css'
	import { onMount } from 'svelte'
	import { goto } from '$app/navigation'
	import { isEditableTarget } from '$lib/utils/keyboard'
	import NavBar from '$components/layout/NavBar.svelte'
	import BottomNav from '$components/layout/BottomNav.svelte'
	import PageTransition from '$components/layout/PageTransition.svelte'
	import Toast from '$components/ui/Toast.svelte'
	import ContextMenu from '$components/ui/ContextMenu.svelte'
	import PersonContextMenu from '$components/ui/PersonContextMenu.svelte'
	import DetailPreviewModal from '$components/modals/DetailPreviewModal.svelte'
	import DiscoverModal from '$components/discover/DiscoverModal.svelte'
	import { loadWatchlist } from '$lib/stores/watchlist'
	import { loadFavoritePeople } from '$lib/stores/people'
	import { loadBlacklist } from '$lib/stores/blacklist'

	let { children } = $props()

	onMount(async () => {
		loadWatchlist()
		loadFavoritePeople()
		loadBlacklist()
		// Register the service worker (client-only, generated by vite-plugin-pwa)
		const { registerSW } = await import('virtual:pwa-register')
		registerSW({ immediate: true })
	})

	let pendingG = $state(false)
	let pendingGTimer: ReturnType<typeof setTimeout> | null = null

	function clearPendingG() {
		pendingG = false
		if (pendingGTimer) {
			clearTimeout(pendingGTimer)
			pendingGTimer = null
		}
	}

	function focusSearch() {
		window.dispatchEvent(new CustomEvent('cinelist:focus-search'))
	}

	function handleGlobalKeydown(e: KeyboardEvent) {
		if (e.defaultPrevented) return
		if (isEditableTarget(e.target)) return

		// Search focus
		if (e.key === '/' && !e.metaKey && !e.ctrlKey && !e.altKey) {
			e.preventDefault()
			clearPendingG()
			focusSearch()
			return
		}
		if ((e.key === 'k' || e.key === 'K') && (e.metaKey || e.ctrlKey) && !e.altKey) {
			e.preventDefault()
			clearPendingG()
			focusSearch()
			return
		}

		// Navigation sequences (GitHub-style)
		if (pendingG) {
			const k = e.key.toLowerCase()
			if (k === 'h') {
				e.preventDefault()
				clearPendingG()
				void goto('/')
				return
			}
			if (k === 'l') {
				e.preventDefault()
				clearPendingG()
				void goto('/library')
				return
			}
			if (k === 's') {
				e.preventDefault()
				clearPendingG()
				void goto('/search')
				return
			}
			clearPendingG()
			return
		}

		if (e.key === 'g' || e.key === 'G') {
			if (e.metaKey || e.ctrlKey || e.altKey) return
			pendingG = true
			if (pendingGTimer) clearTimeout(pendingGTimer)
			pendingGTimer = setTimeout(() => {
				pendingG = false
				pendingGTimer = null
			}, 900)
			return
		}
	}
</script>

<svelte:head>
	<title>CineList</title>
	<meta name="description" content="Your personal movie watchlist" />
</svelte:head>

<a
	href="#main-content"
	class="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[9999] focus:px-4 focus:py-2 focus:rounded-lg focus:text-sm focus:font-semibold focus:shadow-lg"
	style="background: var(--color-amber-500); color: var(--color-surface-950)"
>
	Skip to main content
</a>

<div class="min-h-dvh flex flex-col">
	<NavBar />
	<main id="main-content" class="flex-1 pb-16 sm:pb-0">
		<PageTransition>
			{@render children()}
		</PageTransition>
	</main>
	<BottomNav />
</div>

<svelte:window onkeydown={handleGlobalKeydown} />

<Toast />

<ContextMenu />

<PersonContextMenu />

<DetailPreviewModal />

<DiscoverModal />
