<script lang="ts">
	import '../app.css'
	import { onMount } from 'svelte'
	import NavBar from '$components/layout/NavBar.svelte'
	import BottomNav from '$components/layout/BottomNav.svelte'
	import PageTransition from '$components/layout/PageTransition.svelte'
	import Toast from '$components/ui/Toast.svelte'
	import DetailPreviewModal from '$components/modals/DetailPreviewModal.svelte'
	import { loadWatchlist } from '$lib/stores/watchlist'
	import { loadFavoritePeople } from '$lib/stores/people'

	let { children } = $props()

	onMount(async () => {
		loadWatchlist()
		loadFavoritePeople()
		// Register the service worker (client-only, generated by vite-plugin-pwa)
		const { registerSW } = await import('virtual:pwa-register')
		registerSW({ immediate: true })
	})
</script>

<svelte:head>
	<title>CineList</title>
	<meta name="description" content="Your personal movie watchlist" />
</svelte:head>

<div class="min-h-dvh flex flex-col">
	<NavBar />
	<main class="flex-1 pb-16 sm:pb-0">
		<PageTransition>
			{@render children()}
		</PageTransition>
	</main>
	<BottomNav />
</div>

<Toast />

<DetailPreviewModal />
